import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode,setDarkMode] = useState(false)
  return (
    <div className={ darkMode ? 'dark' : 'light' } >
      <Head>
        <title>Bishop Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 ' >
        <section className='min-h-screen ' >
          <nav className='py-10 mb-12 flex justify-between ' >
            <h1 className='text-xl font-burtons dark:text-white ' >developedbyBish</h1>
            <ul className='flex items-center ' >
              <li> <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode) } className=' cursor-pointer text-2xl dark:text-white  ' /> </li>
              <li> <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8 ' href="#"> Resume</a> </li>
            </ul>
          </nav>
          <div className=' text-center p-10 ' >
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl ' >Benjamin Daly Ndiaye</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white ' >Web and Mobile Developer.</h3>
            <p className=' text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white ' >
              freelancer, je donne des services de devoloppement d'application web et Mobile dependant de vos besoins.
              rejoigner moi ici et et faisons avancer les choses!
            </p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600 ' >
            <AiFillTwitterCircle className='dark:text-white' />
            <AiFillLinkedin className='dark:text-white' />
            <AiFillInstagram className='dark:text-white' />
          </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96     ' >
            <Image src={deved} alt={''} className='fill cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white mx-auto ' >Les Services que j'offre</h3>
            <p className='text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white ' >
              Depuis mes debuts en tant que devolopper, j'ai eu a travailler dans des projets d'ecole, des startup...
              Par la meme occasion j'ai recontrer et de travailler avec des personnes tres talentueux.
            </p>
            <p className='text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white ' >
              J'offre des Services de programmation mais essentiellement du devoloppement d'application et Mobile
              et Web.
            </p>
          </div>
          <div className='lg:flex gap-10' >
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ' >
              <Image className='mx-auto' src={design} alt={''} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 ' >Beau design</h3>
              <p className='py-2 md:text-xl max-w-lg mx-auto  ' >
                Creation de beau design selon vos besoins en utisant les meileurs tech
              </p>
              <h4 className=' py-4 text-teal-600 ' >Mes Technologies utlisees</h4>
              <p className=' text-gray-800 py-1 ' >Photoshop</p>
              <p className=' text-gray-800 py-1 ' >Figma</p>
              <p className=' text-gray-800 py-1 ' >Illustrator</p>

            </div>

            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ' >
              <Image className='mx-auto' src={code} alt={''} width={100} height={100} />
              < h3 className='text-lg font-medium pt-8 pb-2 ' >Beau design</h3>
              <p className='py-2 md:text-xl max-w-lg mx-auto  ' >
                Creation de beau design selon vos besoins en utisant les meileurs te
              </p>
              <h4 className=' py-4 text-teal-600 ' >Mes Technologies utlisees</h4>
              <p className=' text-gray-800 py-1 ' >Photoshop</p>
              <p className=' text-gray-800 py-1 ' >Figma</p>
              <p className=' text-gray-800 py-1 ' >Illustrator</p>
            </div>

            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ' >
              <Image className='mx-auto' src={design} alt={''} width={100} height={100} />
              < h3 className='text-lg font-medium pt-8 pb-2 ' >Beau design</h3>
              <p className='py-2 md:text-xl max-w-lg mx-auto  ' >
                Creation de beau design selon vos besoins en utisant les meileurs te
              </p>
              <h4 className=' py-4 text-teal-600 ' >Mes Technologies utlisees</h4>
              <p className=' text-gray-800 py-1 ' >Photoshop</p>
              <p className=' text-gray-800 py-1 ' >Figma</p>
              <p className=' text-gray-800 py-1 ' >Illustrator</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white ' >Portofolio</h3>
            <p className='text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white ' >
              depuis mes debut en tant que devolopper, j'ai eu a travailler dans des projets d'ecole, des startup
              Par la meme occasion j'ai recontrer et de travailler avec des personnes tres talentueux.
            </p>
          </div >
          <div className="my-4 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className=' basis-1/2 flex-1 '  >
              <Image className=' rounded-lg object-cover shadow-xl '  src={web1} alt={''} style={{width:"100%", height:"100%" }} />
            </div >
            <div className=' basis-1/2 flex-1 '  >
              <Image className=' rounded-lg object-cover' src={web2} alt={''} style={{width:"100%", height:"100%" }} />
            </div  >
            <div className=' basis-1/2 flex-1 '  >
              <Image className=' rounded-lg object-cover' src={web3} alt={''} style={{width:"100%", height:"100%" }} />
            </div>
            <div  className=' basis-1/2 flex-1 '  >
              <Image  className=' rounded-lg object-cover' src={web4} alt={''} style={{width:"100%", height:"100%" }} />
            </div>
            <div className=' basis-1/2 flex-1 '  >
              <Image className=' rounded-lg object-cover' src={web5} alt={''} style={{width:"100%", height:"100%" }} />
            </div>
            <div className=' basis-1/2 flex-1 '  >
              <Image className=' rounded-lg object-cover' src={web6} alt={''} style={{width:"100%", height:"100%" }} />
            </div>
          </div>
        </section>

      </main>
    </div>
  )
}
